<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.darkignite.proximityantixray</groupId>
  <artifactId>proximityantixray-parent</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <name>ProximityAntiXray-Parent</name>
  <description>Ultra-lightweight proximity-based spawner and structure hider against Freecam and ESP for Paper Minecraft servers.</description>
  <modules>
    <module>Libs</module>
    <module>ProximityAntiXray</module>
  </modules>
  <properties>
    <minecraftVersion>1.21.4</minecraftVersion>
    <paperVersion>${minecraftVersion}-R0.1-SNAPSHOT</paperVersion>
  </properties>
</project>
